# Desabilitar algumas regras específicas que podem não ser relevantes para o seu projeto.
disabled_rules:   
  - identifier_name      


opt_in_rules:
  - empty_count

included:

excluded:
  - Pods/        
  - Carthage
  - Digio/AppDelegate.swift       
  - Digio/SceneDelegate.swift      

line_length:
  warning: 120           
  error: 200             
  ignores_comments: true 
  ignores_interpolated_strings: true 


type_name:
  min_length: 3          
  max_length: 40         
  excluded:
    - ID
    - URL
    - HTTP

function_body_length:
  warning: 40            
  error: 75              
  ignores_comments: true 
  ignores_empty_lines: true 


custom_rules:
  disable_print:
    included: ".*\\.swift"
    name: "print usage"
    regex: "((\\bprint)|(Swift\\.print))\\s*\\("
    message: "Prefer os_log over print"
    severity: warning